#!/usr/bin/env python3
"""Deterministic paper-to-theme coverage checker and assignment report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import yaml


THEME_BY_DOMAIN = {
    "domain:2d-layered": "theme-2d-epitaxy-growth",
    "domain:catalysis-surfaces": "theme-catalysis-surfaces",
    "domain:ferroelectrics-polar": "theme-ferroelectrics-polar-oxides",
    "domain:ml-atomistic": "theme-ml-atomistic-potentials",
    "domain:water-silica-geo": "theme-water-silica-geo",
    "domain:organics-polymers-pyrolysis": "theme-pyrolysis-combustion-organics",
    "domain:fuel-combustion": "theme-combustion-flames-fuels",
    "domain:oxides-ceramics": "theme-oxides-silica-ceramics",
    "domain:reaxff-lineage": "theme-reactive-md-corpus",
    "domain:reactive-md": "theme-reactive-md-corpus",
    "domain:methods-software": "theme-reactive-md-corpus",
    "domain:classical-ff-specialized": "theme-reactive-md-corpus",
    "domain:batteries-electrochemistry": "theme-reactive-md-corpus",
    "domain:mechanics-tribology": "theme-2d-epitaxy-growth",
    "domain:carbon-hydrocarbon": "theme-pyrolysis-combustion-organics",
    "domain:alloys-metallurgy": "theme-oxides-silica-ceramics",
}

THEME_BY_MATERIAL = {
    "material:tmd": "theme-2d-epitaxy-growth",
    "material:graphene-carbon-nano": "theme-2d-epitaxy-growth",
    "material:hexagonal-boron-nitride": "theme-2d-epitaxy-growth",
    "material:zeolite-porous": "theme-porous-mof-zeolite",
    "material:silicate-glass": "theme-oxides-silica-ceramics",
    "material:oxide": "theme-oxides-silica-ceramics",
    "material:perovskite-oxide": "theme-ferroelectrics-polar-oxides",
    "material:polymer-organic": "theme-pyrolysis-combustion-organics",
}

THEME_BY_METHOD = {
    "method:reaxff": "theme-reactive-md-corpus",
    "method:ereaxff": "theme-reactive-md-corpus",
    "method:reactive-md-generic": "theme-reactive-md-corpus",
    "method:enhanced-sampling": "theme-reactive-md-corpus",
    "method:ml-potential": "theme-ml-atomistic-potentials",
}

THEME_FALLBACK = "theme-reactive-md-corpus"


def parse_frontmatter(path: Path) -> Dict:
    txt = path.read_text(encoding="utf-8")
    if not txt.startswith("---"):
        return {}
    parts = txt.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return {}


def assign_themes(tags: List[str]) -> List[str]:
    themes: List[str] = []
    for tag in tags:
        if tag in THEME_BY_DOMAIN and THEME_BY_DOMAIN[tag] not in themes:
            themes.append(THEME_BY_DOMAIN[tag])
    for tag in tags:
        if tag in THEME_BY_MATERIAL and THEME_BY_MATERIAL[tag] not in themes:
            themes.append(THEME_BY_MATERIAL[tag])
    for tag in tags:
        if tag in THEME_BY_METHOD and THEME_BY_METHOD[tag] not in themes:
            themes.append(THEME_BY_METHOD[tag])
    if not themes:
        themes = [THEME_FALLBACK]
    return themes


def collect_assignments(papers_dir: Path) -> Tuple[List[Dict], List[Dict]]:
    rows: List[Dict] = []
    unresolved: List[Dict] = []
    for path in sorted(papers_dir.glob("*.md")):
        if path.name in {"index.md"} or path.name.startswith("._"):
            continue
        fm = parse_frontmatter(path)
        if fm.get("type") != "paper":
            continue
        pid = fm.get("id", "")
        slug = pid.split(":", 1)[1] if ":" in pid else path.stem
        tags = fm.get("canonical_tags") or []
        themes = assign_themes(tags)
        row = {
            "paper_id": pid or f"paper:{slug}",
            "slug": slug,
            "themes": themes,
            "canonical_tags": tags,
            "path": str(path.as_posix()),
        }
        rows.append(row)
        if not themes:
            unresolved.append(row)
    return rows, unresolved


def write_markdown_report(rows: List[Dict], unresolved: List[Dict], out_md: Path) -> None:
    theme_counts: Dict[str, int] = {}
    for row in rows:
        for theme in row["themes"]:
            theme_counts[theme] = theme_counts.get(theme, 0) + 1

    lines: List[str] = []
    lines.append("# Paper-to-theme coverage report")
    lines.append("")
    lines.append("Generated by `scripts/check_paper_theme_coverage.py`.")
    lines.append("")
    lines.append(f"- Total `paper:` pages scanned: **{len(rows)}**")
    lines.append(f"- Papers with at least one assigned theme: **{len(rows) - len(unresolved)}**")
    lines.append(f"- Unassigned papers: **{len(unresolved)}**")
    lines.append("")
    lines.append("## Theme assignment counts")
    lines.append("")
    lines.append("| Theme | Papers assigned |")
    lines.append("|------|-----------------:|")
    for theme, count in sorted(theme_counts.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"| `{theme}` | {count} |")
    lines.append("")
    lines.append("## Unassigned papers")
    lines.append("")
    if not unresolved:
        lines.append("All papers are assigned to at least one theme.")
    else:
        lines.append("| Paper ID | Slug | Path |")
        lines.append("|----------|------|------|")
        for row in unresolved:
            lines.append(f"| `{row['paper_id']}` | `{row['slug']}` | `{row['path']}` |")
    lines.append("")
    out_md.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--papers-dir", default="wiki/papers", help="Directory containing paper markdown pages.")
    ap.add_argument(
        "--out-md",
        default="outputs/paper_theme_coverage.md",
        help="Markdown report output path.",
    )
    ap.add_argument(
        "--out-json",
        default="outputs/paper_theme_assignments.json",
        help="JSON assignment artifact output path.",
    )
    args = ap.parse_args()

    papers_dir = Path(args.papers_dir)
    out_md = Path(args.out_md)
    out_json = Path(args.out_json)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.parent.mkdir(parents=True, exist_ok=True)

    rows, unresolved = collect_assignments(papers_dir)
    write_markdown_report(rows, unresolved, out_md)
    out_json.write_text(json.dumps(rows, indent=2), encoding="utf-8")

    print(f"wrote {out_md} — {len(unresolved)} unassigned of {len(rows)} papers")
    print(f"wrote {out_json} — {len(rows)} assignments")

    if unresolved:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
