#!/usr/bin/env python3
"""Split paper wiki pages into batch files for LLM curation passes.

Use when you want **parallel agents or sessions**: each batch file lists one slug per line
(`wiki/papers/{slug}.md`). Default **batch size is 200** (~7 passes for ~1278 papers).

Mechanical only: does not call an LLM. Regenerate after removing `phase4-stub-pending-curation`
from pages you have finished.

Examples:

  python3 scripts/paper_curation_batches.py
  python3 scripts/paper_curation_batches.py --batch-size 200 --mode pending
  python3 scripts/paper_curation_batches.py --mode all --batch-size 200
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from phase5_retrieval_lib import ROOT, WIKI, parse_frontmatter

PAPERS = WIKI / "papers"
SKIP = {"index.md"}
STUB_PHRASE = "Phase 4 mechanical stub"
STUB_TAG = "phase4-stub-pending-curation"


def is_pending_stub(meta: dict, body: str) -> bool:
    tags = meta.get("candidate_tags")
    if isinstance(tags, list) and STUB_TAG in tags:
        return True
    if STUB_PHRASE in body[:12000]:
        return True
    return False


def collect_slugs(mode: str) -> list[str]:
    slugs: list[str] = []
    for path in sorted(PAPERS.glob("*.md")):
        if path.name in SKIP:
            continue
        raw = path.read_text(encoding="utf-8", errors="replace")
        meta, body = parse_frontmatter(raw)
        if meta.get("type") != "paper":
            continue
        if mode == "pending":
            if not is_pending_stub(meta, body):
                continue
        elif mode == "all":
            pass
        else:
            raise ValueError(mode)
        slugs.append(path.stem)
    slugs.sort()
    return slugs


def chunk(slugs: list[str], batch_size: int) -> list[list[str]]:
    out: list[list[str]] = []
    for i in range(0, len(slugs), batch_size):
        out.append(slugs[i : i + batch_size])
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--batch-size",
        type=int,
        default=200,
        help="slugs per batch file (default: 200)",
    )
    ap.add_argument(
        "--mode",
        choices=("pending", "all"),
        default="pending",
        help="pending = stub-tagged or mechanical-stub body; all = every paper page",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=ROOT / "outputs" / "curation_batches",
        help="output directory (default: outputs/curation_batches)",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="print counts only; do not write files",
    )
    args = ap.parse_args()
    if args.batch_size < 1:
        ap.error("--batch-size must be >= 1")

    slugs = collect_slugs(args.mode)
    batches = chunk(slugs, args.batch_size)

    if args.dry_run:
        print(f"mode={args.mode} batch_size={args.batch_size}")
        print(f"total_slugs={len(slugs)} batches={len(batches)}")
        for i, b in enumerate(batches, start=1):
            print(f"  batch-{i:03d}: {len(b)}")
        return

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "mode": args.mode,
        "batch_size": args.batch_size,
        "total_slugs": len(slugs),
        "n_batches": len(batches),
        "batches": [
            {"file": f"batch-{i:03d}.txt", "count": len(b)} for i, b in enumerate(batches, start=1)
        ],
    }

    for i, batch in enumerate(batches, start=1):
        p = out_dir / f"batch-{i:03d}.txt"
        p.write_text("\n".join(batch) + ("\n" if batch else ""), encoding="utf-8")

    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )

    readme = out_dir / "_README.md"
    readme.write_text(
        """# Paper curation batches (LLM passes)

Generated by `scripts/paper_curation_batches.py`. Each `batch-NNN.txt` is **one slug per line**
(stem of `wiki/papers/{slug}.md`).

## Parallel workflow

- Run **several Cursor agents** (or humans) at once: assign **one batch file per agent**.
- Typical batch size: **200** papers per pass (~7 passes for a full corpus of ~1278 pages).
- After a batch is curated, remove `phase4-stub-pending-curation` from `candidate_tags` and replace stub prose; then regenerate batches so finished work drops out of `--mode pending`.

## Regenerate

```bash
python3 scripts/paper_curation_batches.py --batch-size 200 --mode pending
```

Full list (including already curated pages), e.g. for a second editorial pass:

```bash
python3 scripts/paper_curation_batches.py --batch-size 200 --mode all
```

See `docs/PHASE4_RUNBOOK.md` for Phase 4 policy.
""",
        encoding="utf-8",
    )

    print(
        f"wrote {len(batches)} batch file(s) to {out_dir} "
        f"({len(slugs)} slugs, mode={args.mode}, batch_size={args.batch_size})"
    )


if __name__ == "__main__":
    main()
