#!/usr/bin/env python3
"""Mechanical report: wiki paper page 'richness' for Stage A enrichment backlog.

Does not invent science — counts words and detects section headings only.

Default richness rule (override with env or flags):
  - body word count >= MIN_WORDS (default 400)
  - body contains '## Summary' (case-sensitive ##)
  - body contains '## Methods'
  - body contains '## Findings'

Papers failing any check are listed as backlog candidates. Cross-check
docs/corpus/NON_PRIMARY_ARTICLE_PAPER_SLUGS.md for SI/galley/pointer roles
that may legitimately stay shorter after operator review.

Usage:
  python3 scripts/report_paper_richness.py
  python3 scripts/report_paper_richness.py --min-words 350 --output outputs/paper_richness_backlog.md
  python3 scripts/report_paper_richness.py --write-batch outputs/curation_batches/rich-paper-wave-001.txt --batch-size 80
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from phase5_retrieval_lib import WIKI, parse_frontmatter

PAPERS = WIKI / "papers"
SKIP = {"index.md"}


def body_word_count(body: str) -> int:
    body = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", body)
    return len(re.findall(r"\S+", body))


def has_heading(body: str, name: str) -> bool:
    return bool(re.search(rf"^##\s+{re.escape(name)}\s*$", body, re.MULTILINE | re.IGNORECASE))


def analyze(path: Path) -> dict:
    raw = path.read_text(encoding="utf-8", errors="replace")
    meta, body = parse_frontmatter(raw)
    wc = body_word_count(body)
    return {
        "slug": path.stem,
        "words": wc,
        "has_summary": has_heading(body, "Summary"),
        "has_methods": has_heading(body, "Methods"),
        "has_findings": has_heading(body, "Findings"),
        "type": meta.get("type"),
    }


def rich_enough(row: dict, min_words: int) -> bool:
    if row.get("type") != "paper":
        return True  # don't backlog non-paper files in papers/
    return (
        row["words"] >= min_words
        and row["has_summary"]
        and row["has_methods"]
        and row["has_findings"]
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--min-words", type=int, default=400, help="minimum body word count (default 400)")
    ap.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "outputs" / "paper_richness_backlog.md",
    )
    ap.add_argument(
        "--write-batch",
        type=Path,
        default=None,
        help="Write first N backlog slugs (one per line) to this path",
    )
    ap.add_argument("--batch-size", type=int, default=80, help="with --write-batch, max slugs (default 80)")
    args = ap.parse_args()

    rows: list[dict] = []
    for path in sorted(PAPERS.glob("*.md")):
        if path.name in SKIP or path.name.startswith("._"):
            continue
        rows.append(analyze(path))

    backlog = [r for r in rows if not rich_enough(r, args.min_words)]
    backlog.sort(key=lambda r: (r["words"], r["slug"]))

    lines = [
        "# Paper richness backlog (mechanical)",
        "",
        f"Generated by `scripts/report_paper_richness.py` with `--min-words {args.min_words}`.",
        "",
        "**Rich** = type `paper` AND word count ≥ threshold AND headings `## Summary`, `## Methods`, `## Findings` present.",
        "",
        "**Exceptions:** Slugs listed in [`docs/corpus/NON_PRIMARY_ARTICLE_PAPER_SLUGS.md`](../docs/corpus/NON_PRIMARY_ARTICLE_PAPER_SLUGS.md) (SI-only, galley duplicates, legacy manifests) may stay shorter **after operator review**—do not bulk-expand without checking corpus role.",
        "",
        "## Summary counts",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total `wiki/papers/*.md` (excl. index, `._*`) | {len(rows)} |",
        f"| Meets richness rule | {len(rows) - len(backlog)} |",
        f"| Backlog (need enrichment) | {len(backlog)} |",
        "",
        "## Backlog (sorted by word count ascending)",
        "",
        "| Slug | Words | Summary | Methods | Findings |",
        "|------|-------|---------|---------|----------|",
    ]

    for r in backlog:
        ys = "yes" if r["has_summary"] else "no"
        ym = "yes" if r["has_methods"] else "no"
        yf = "yes" if r["has_findings"] else "no"
        lines.append(f"| `{r['slug']}` | {r['words']} | {ys} | {ym} | {yf} |")

    lines.extend(
        [
            "",
            "## Commands",
            "",
            "```bash",
            "python3 scripts/report_paper_richness.py --min-words 400 -o outputs/paper_richness_backlog.md",
            "python3 scripts/report_paper_richness.py --write-batch outputs/curation_batches/rich-paper-wave-001.txt --batch-size 80",
            "```",
            "",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.output} — {len(backlog)} backlog of {len(rows)} papers")

    if args.write_batch and backlog:
        out = args.write_batch
        out.parent.mkdir(parents=True, exist_ok=True)
        slugs = [r["slug"] for r in backlog[: args.batch_size]]
        out.write_text("\n".join(slugs) + "\n", encoding="utf-8")
        print(f"wrote batch {out} ({len(slugs)} slugs)")


if __name__ == "__main__":
    main()
